# module du helios launcher
name: Launcher Build
on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: create env file
        run: |
          touch .env
          echo ApiKey=${{ secrets.API_KEY }} >> .env

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          APIKEY: ${{ secrets.APIKEY }}
        run: npm run deploy
        shell: bash
